import { LeadService } from './lead-service'
import { CampaignService } from './campaign-service'
import { AnalyticsService } from './analytics-service'
import { AlertService } from './alert-service'
import { CompanyService } from './company-service'
import { AdminService } from './admin-service'
import { AuthService } from './auth-service'
import { CompanyProfileService } from './company-profile-service'
import { ProductService } from './product-service'
import { KnowledgeService } from './knowledge-service'
import { ReadinessService } from './readiness-service'
import { ConversationService } from './conversation-service'
import { AgentService } from './agent-service'
import { HealthService } from './health-service'

export const leadService = new LeadService()
export const campaignService = new CampaignService()
export const analyticsService = new AnalyticsService()
export const alertService = new AlertService()
export const companyService = new CompanyService()
export const adminService = new AdminService()
export const authService = new AuthService()
export const companyProfileService = new CompanyProfileService()
export const productService = new ProductService()
export const knowledgeService = new KnowledgeService()
export const readinessService = new ReadinessService()
export const conversationService = new ConversationService()
export const agentService = new AgentService()
export const healthService = new HealthService()
