import { AuthService } from './auth-service'
import { ChatService } from './chat-service'
import { AppointmentService } from './appointment-service'
import { CalendarConfigService } from './calendar-config-service'
import { PlanService } from './plan-service'
import { AdminUserService } from './admin-user-service'
import { AdminDashboardService } from './admin-dashboard-service'
import { AdminUserDataService } from './admin-user-data-service'
import { WhatsAppService } from './whatsapp-service'
import { ChannelAccountService } from './channel-account-service'
import { LeadService } from './lead-service'
import { FinanceService } from './finance-service'
import { AgentConfigService } from './agent-config-service'

export const authService = new AuthService()
export const chatService = new ChatService()
export const appointmentService = new AppointmentService()
export const calendarConfigService = new CalendarConfigService()
export const planService = new PlanService()
export const adminUserService = new AdminUserService()
export const adminDashboardService = new AdminDashboardService()
export const adminUserDataService = new AdminUserDataService()
export const whatsAppService = new WhatsAppService()
export const channelAccountService = new ChannelAccountService()
export const leadService = new LeadService()
export const financeService = new FinanceService()
export const agentConfigService = new AgentConfigService()
